### ISSUE TITLE
introduction - host / services 

### ISSUE THREAD

**Issue by mglt** [Abhayakara/draft-ietf-homenet-simple-naming-arch#1]
> Associating domain names with hosts on the Internet is a key factor
   in enabling communication with hosts, particularly for service
   discovery.

My understanding of the first sentence is that domain are associated to hosts. Even thought the sentence following mentions service discovery, I believe we should clarify that names are not restricted to designating hosts only, but can also be used to designate service as well. I think the following sentences would be clarifying and provide more context to the reader.

> Associating domain names with hosts on the Internet is a key factor
   in enabling communication between hosts.  Names are used as a
   convenient identifier that most of the time conveys some sort of
   meanings.  This eases end users to remember and avoids
   missconfigurations errors while typing such identifiers as it would
   be the case with an IP address or any randomly generated identifier.

   Within home network, in addition to enabling host to host
   communications that are resilient to renumbering, domain name are
   also heavily used to publish the services that are available within
   the home network as well as to enable a end user to discover such
   services in a convenient way.

**Comment by Abhayakara** [comment]
What you've done here is to add several sentences to a single sentence, making the text longer and harder to read, in service of a point that I don't think belongs in the first paragraph of an architecture document.   It's true that we need names on the homenet because it sucks to discover and type IP addresses, but that's not a point we need to make _here_.

I do agree that this text needs work, but I don't think this information belongs here.

**Comment by mglt** [comment]
As long as the text makes it clear that we are not only focused on hosts but also on services I am fine. It can be shorter of course  then what I proposed.

**Comment by Abhayakara** [comment]
I think this is a good point—I hadn't understood that that was the issue, so it's good that we went back and forth on it.   I will try to come up with some text that addresses your issue and makes me happier.

**Comment by Abhayakara** [comment]
What I would suggest is that we break the first paragraph in two and rephrase it as follows:

This document describes a simple architecture for providing name service and service discovery for homenets.  This allows hosts to use the Domain Name System to discover services and the hosts providing those services, whether they are on the home network or the Internet.

This simple architecture is intended to serve as a foundational architecture for naming on home networks.   It is expected that all homenet routers will implement this architecture.   It is intended that an additional architecture document will complete the task laid out in IPv6 Home Networking Architecture Principles [RFC7368].

Consequently, this simple architecture leaves several requirements from RFC7368 unaddressed:
- Publication of names on the homenet for general use on the internet
- Publication of names on the homenet for use by authorized users of the homenet when connected to other networks.
- Secure delegation, enabling DNSSEC validation of names published on the homenet.

**Comment by Abhayakara** [comment]
Document updated.
