### ISSUE TITLE
introduction: clarification of simple way 

### ISSUE THREAD

**Issue by mglt** [Abhayakara/draft-ietf-homenet-simple-naming-arch#2]
> This document describes a simple way of providing name
   service and service discovery for homenets.

My understanding is that the document also provides an analysis and requirements for the architecture as well as the architecture itself. I am proposing the following text to be a little bit more explicit for "simple way".

> This document describes a simple naming architecture that fulfills
   the expectations and constraints foreseen by the average home
   network.  Such home network are typically a subset of the more
   generic home network described in [8] and is designated as the Simple
   Home Network or simply home network in this document.  The document
   does not intent to provide a full and complete naming architecture
   that can be achieved with additional skills and settings.

**Comment by Abhayakara** [comment]
How about:

This document describes a simple architecture for providing name service and service discovery on homenets.  It provides a subset of the functionality described in the Homenet Architecture [8], and is intended to serve both as a feature set for minimal homenet routers, and to provide a foundation for a complete homenet architecture that allows such minimal routers to provide full naming and service discovery when at least one fully-functional homenet router is present on the home network.

**Comment by mglt** [comment]
sounds good to me. Thanks for proposing the text.

**Comment by Abhayakara** [comment]
Document updated.
