### ISSUE TITLE
Specificities / requirements of the simple homenet architecture

### ISSUE THREAD

**Issue by mglt** [Abhayakara/draft-ietf-homenet-simple-naming-arch#4]
I believe the text below coudl be placed in a dedicated section listing the requirements or specificities.
>    Homenet adds the following considerations:

   1.  Some names may be published in a broader scope than others.  For
       example, it may be desirable to advertise some homenet services
       to users who are not connected to the homenet.  However, it is
       unlikely that all services published on the home network would be
       appropriate to publish outside of the home network.  In many
       cases, no services will be appropriate to publish outside of the
       network, but the ability to do so is required.

   2.  Users cannot be assumed to be skilled or knowledgeable in name
       service operation, or even to have any sort of mental model of
       how these functions work.  All of the operations mentioned here
       must reliably function automatically, without any user
       intervention or debugging.

   3.  Because user intervention cannot be required, naming conflicts
       must be resolved automatically, and, to the extent possible,
       transparently.

   4.  Hosts that do not implement any homenet-specific capabilities
       must still be able to discover and access services on the
       homenet, to the extent possible.

   5.  Devices that provide services must be able to publish those
       services on the homenet, and those services must be available
       from any part of the homenet, not just the link to which the
       device is attached.

   6.  Homenet explicitly supports multihoming--connecting to more than
       one Internet Service Provider--and therefore support for multiple
       provisioning domains [6] is required to deal with situations
       where the DNS may give a different answer depending on whether
       caching resolvers at one ISP or another are queried.

**Comment by Abhayakara** [comment]
This looks like the requirements from the old architecture document, which aren't applicable here, although a subset of them are.

Action item: come up with the list that's applicable to simple homenet naming.

**Comment by mglt** [comment]
I do not updated its content so we could follow the diff. My point was more to have a dedicated section for this rather then having this in the intro. I will update the list.

**Comment by Abhayakara** [comment]
I've updated the text so that it says "the simple homenet naming architecture adds the following requirements" and then leaves out the ones that aren't covered by the shna.   :)
